apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: aegisnexus
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: aegisnexus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backend-role
  namespace: aegisnexus
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-role-binding
  namespace: aegisnexus
subjects:
  - kind: ServiceAccount
    name: backend-sa
roleRef:
  kind: Role
  name: backend-role
  apiGroup: rbac.authorization.k8s.io
